server:
  port: 8001
spring:
  application:
    name: transport-feign
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sboot?characterEncoding=utf-8&serverTimezone=UTC
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka